require("impatient")
-- without config 
require('Comment').setup()
require("colorizer").setup()
require("nvim-lsp-installer").setup()
-- modules
require("modules.theme")
require('modules.lsp')
require('modules.statusline')
require('modules.filetree')
require('modules.bufferline')
require('modules.terminal')
require('modules.git')
require('modules.treesitter')
require('modules.filetype')
require('modules.wildmenu')
require('modules.illuminate')
require('modules.snip')
require('modules.whichkey')
require('modules.telescope')
require('modules.hop')
require('modules.dashboard')
require('modules.accelerate')
